apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: crud-app
spec:
  ports:
  - protocol: TCP
    port: 5432
    name: dbport
    targetPort: 5432
  type: ClusterIP
  selector:
    service: db
