apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - name: db
          image: postgres:16
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-password
            - name: POSTGRES_DB
              value: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: crud-app-pvc
