apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: posgres
spec:
  ports:
  - protocol: TCP
    port: 5432
    name: dbport
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres
