apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crud-app-pvc
  namespace: crud-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
