apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: crud-app
          ports:
            - containerPort: 8000
          env:
            - name: db_address
              value: db
            - name: db_username
              value: postgres
            - name: db_name
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
      restartPolicy: Always
